name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:
  push:
    branches:
      - main
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - milestoned
      - demilestoned
      - locked
      - unlocked

permissions:
  contents: write


jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch Open Issues and Update README
        run: |
          issues=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues?state=open" | \
          jq -r '.[] | select(.labels | map(.name) | index("frontend")) | "- [#\(.number)](\(.html_url)) \(.title)"')

          awk -v new="$issues" '
            /<!-- ISSUES-START -->/ { print; print new; skip=1; next }
            /<!-- ISSUES-END -->/ { skip=0 }
            skip == 0 { print }
          ' README.md > tmp && mv tmp README.md

      - name: Install Octokit
        run: npm install @octokit/core --no-save

      - name: Run Checklist Script
        run: node .github/scripts/update-parent-checklist.cjs
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global core.autocrlf false

          git pull origin main --rebase || git rebase --abort

          git add README.md
          git diff --cached --quiet || git commit -m "🔄 Auto-update README with open issues"
          git push